"""Generate the game atlas + typed Rust sprite table from the ORIGINAL PICT
resources (the authentic runtime graphics), not the author's FullPaint sketch.

Each PICT is decoded from the recovered resource fork and sliced into individual
sprites using the exact offsets from `CreateOffScreenRects` in StuntCopter.pas.
The PICTs are clean, so no divider/speck cleanup is needed. Sprites are packed
with a transparent gutter; ink becomes opaque white (tint at draw time).
"""

import os
import re
import sys
import numpy as np
from PIL import Image

sys.path.insert(0, os.path.dirname(__file__))
from pict import read_ad_rsrc, get_pict, decode_pict

REF = r"D:\training\opensc\reference\stuntcopter"
ASSETS = r"D:\training\opensc\assets"
SRC = r"D:\training\opensc\src"
PAD = 2
ATLAS_W = 512

rf = read_ad_rsrc(os.path.join(REF, "StuntCopter.Rsrc.appledouble"))


def pict(pid):
    bits, _ = decode_pict(get_pict(rf, pid))  # HxW bool, True = black ink
    return bits


COPTER, MAN, SCOREBOX = pict(128), pict(129), pict(130)
CLOUD1, CLOUD2, CLOUD3 = pict(356), pict(357), pict(358)


def whole(bits):
    return (bits, 0, 0, bits.shape[1], bits.shape[0])


# name -> (source bits, x, y, w, h), offsets from CreateOffScreenRects.
S = {}
for i in range(3):
    S[f"copter_{i+1}"] = (COPTER, i * 74, 0, 74, 26)
    S[f"wagon_{i+1}"] = (COPTER, i * 73, 26, 73, 22)
for i in range(7):
    S[f"flip_{i+1:02d}"] = (COPTER, i * 32, 48, 32, 41)
    S[f"flip_{i+8:02d}"] = (COPTER, i * 32, 89, 32, 41)
_TOP = ["man_hang", "man_drop1", "man_drop2", "man_drop3", "man_drop4", "man_drop5", "man_thumbup"]
_BOT = ["man_splat1", "man_splat2", "man_splat3", "man_splat4", "man_splat5", "man_splat6", "man_thumbdown"]
for i in range(7):
    S[_TOP[i]] = (MAN, i * 14, 0, 14, 16)
    S[_BOT[i]] = (MAN, i * 14, 16, 14, 16)
for i in range(5):
    S[f"num_{i}"] = (MAN, i * 20, 32, 20, 15)
    S[f"num_{i+5}"] = (MAN, i * 20, 47, 20, 15)
S["cross"] = (MAN, 0, 62, 81, 81)
S["man_in_wagon"] = (MAN, 81, 62, 28, 10)
S["driver"] = (MAN, 81, 72, 40, 22)
S["horse_dead"] = (MAN, 81, 94, 29, 22)
S["cloud_left"] = whole(CLOUD3)
S["cloud_bottom"] = whole(CLOUD2)
S["cloud_right"] = whole(CLOUD1)
S["scorebox"] = whole(SCOREBOX)


def silhouette(spec):
    bits, x, y, w, h = spec
    sub = bits[y:y + h, x:x + w]
    rgba = np.zeros((*sub.shape, 4), dtype=np.uint8)
    rgba[sub] = (255, 255, 255, 255)
    return Image.fromarray(rgba, "RGBA")


def ident(name):
    return "".join(part.capitalize() for part in re.split(r"[_]+", name))


sprites = [(n, silhouette(S[n])) for n in sorted(S)]
sprites.sort(key=lambda s: (-s[1].height, s[0]))

placements = {}
cur_x, cur_y, row_h = PAD, PAD, 0
for name, img in sprites:
    if cur_x + img.width + PAD > ATLAS_W:
        cur_x, cur_y, row_h = PAD, cur_y + row_h + PAD, 0
    placements[name] = (cur_x, cur_y, img.width, img.height)
    cur_x += img.width + PAD
    row_h = max(row_h, img.height)
atlas_h = cur_y + row_h + PAD

atlas = Image.new("RGBA", (ATLAS_W, atlas_h), (0, 0, 0, 0))
for name, img in sprites:
    x, y, _, _ = placements[name]
    atlas.paste(img, (x, y))
atlas.save(os.path.join(ASSETS, "atlas.png"))
print("atlas.png", atlas.size)

variants = [(ident(n), n) for n in sorted(S)]
lines = [
    "// @generated by scripts/gen_atlas.py from the original PICT resources.",
    "// Do not edit by hand. Regenerate to change sprite rects.",
    "//",
    "// Each rect is a padded source rectangle within `atlas.png`.",
    "#![allow(dead_code)]",
    "#![allow(clippy::too_many_lines)]",
    "",
    "use macroquad::math::Rect;",
    "",
    "/// A sprite region within the packed atlas texture.",
    "#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]",
    "pub enum Sprite {",
]
for var, orig in variants:
    lines += [f"    /// `{orig}`", f"    {var},"]
lines += ["}", "", "impl Sprite {",
          "    /// Source rectangle of this sprite within the atlas texture, in pixels.",
          "    #[must_use]", "    #[rustfmt::skip]", "    pub const fn rect(self) -> Rect {",
          "        match self {"]
for var, orig in variants:
    x, y, w, h = placements[orig]
    lines.append(f"            Self::{var} => Rect {{ x: {x}.0, y: {y}.0, w: {w}.0, h: {h}.0 }},")
lines += ["        }", "    }", "}", ""]
open(os.path.join(SRC, "atlas.rs"), "w", newline="\n", encoding="utf-8").write("\n".join(lines))
print("src/atlas.rs", len(variants), "sprites,", "atlas", ATLAS_W, "x", atlas_h)

# Contact sheet for verification.
cols = 8
cw, ch = 92, 92
rows = (len(variants) + cols - 1) // cols
sheet = Image.new("RGB", (cols * cw, rows * ch), (210, 210, 210))
from PIL import ImageDraw
d = ImageDraw.Draw(sheet)
comp = Image.alpha_composite(Image.new("RGBA", atlas.size, (210, 210, 210, 255)), atlas).convert("RGB")
for idx, (var, orig) in enumerate(variants):
    x, y, w, h = placements[orig]
    sp = comp.crop((x, y, x + w, y + h))
    sc = min((cw - 6) / w, (ch - 14) / h, 4)
    sp = sp.resize((max(1, int(w * sc)), max(1, int(h * sc))), Image.NEAREST)
    cx, cy = (idx % cols) * cw, (idx // cols) * ch
    sheet.paste(sp, (cx + 3, cy + 2))
    d.rectangle([cx, cy, cx + cw - 1, cy + ch - 1], outline=(150, 150, 150))
    d.text((cx + 2, cy + ch - 11), orig, fill=(150, 0, 0))
sheet.save(r"C:\Users\MikaelBeyene\AppData\Local\Temp\claude\D--training-opensc\68a8ed9d-2ec2-4fb7-9ee2-ba32e48ffa1f\scratchpad\contact_pict.png")
print("contact sheet saved")
