"""Generate a crisp 1-bit bitmap font atlas + Rust glyph table.

Antialiased TTF text turns to mush when the low-res virtual canvas is
nearest-scaled. So we bake glyphs to a 1-bit atlas once (Arial Bold, thresholded)
and blit them as pixel sprites — sharp at any zoom. White on transparency, so the
game can tint them.
"""

import os
import numpy as np
from PIL import Image, ImageFont, ImageDraw

ASSETS = r"D:\training\opensc\app\assets"
SRC = r"D:\training\opensc\app\src"
FONT_PATH = r"C:\Windows\Fonts\arialbd.ttf"
SIZE = 12
CELL_H = 13          # fixed cell height so all glyphs share a baseline
BASELINE = 10        # y of the text baseline within the cell
PAD = 1
ATLAS_W = 256

CHARS = " 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
font = ImageFont.truetype(FONT_PATH, SIZE)


def render(ch):
    """Return (1-bit ink array of shape (CELL_H, w), advance) for a glyph."""
    advance = round(font.getlength(ch))
    w = max(advance + 1, 1)
    img = Image.new("L", (w + 2, CELL_H), 0)
    draw = ImageDraw.Draw(img)
    draw.text((0, BASELINE), ch, font=font, fill=255, anchor="ls")
    ink = np.array(img) > 128
    return ink, advance


glyphs = {ch: render(ch) for ch in CHARS}

# Shelf-pack the non-empty glyphs (space has no ink).
placements = {}
cur_x, cur_y, row_h = PAD, PAD, 0
for ch in CHARS:
    ink, _ = glyphs[ch]
    w = ink.shape[1]
    if int(ink.sum()) == 0:
        continue
    if cur_x + w + PAD > ATLAS_W:
        cur_x, cur_y, row_h = PAD, cur_y + row_h + PAD, 0
    placements[ch] = (cur_x, cur_y, w, CELL_H)
    cur_x += w + PAD
    row_h = max(row_h, CELL_H)
atlas_h = cur_y + row_h + PAD

atlas = np.zeros((atlas_h, ATLAS_W, 4), dtype=np.uint8)
for ch, (x, y, w, h) in placements.items():
    ink = glyphs[ch][0]
    for j in range(h):
        for i in range(w):
            if ink[j, i]:
                atlas[y + j, x + i] = (255, 255, 255, 255)
Image.fromarray(atlas, "RGBA").save(os.path.join(ASSETS, "font.png"))
print("font.png", (ATLAS_W, atlas_h))

# Emit the glyph table.
def esc(ch):
    return {" ": "' '", "'": "'\\''", "\\": "'\\\\'"}.get(ch, f"'{ch}'")

lines = [
    "// @generated by scripts/gen_font.py -- do not edit by hand.",
    "//",
    "// A 1-bit bitmap font (Arial Bold, thresholded) for crisp HUD text.",
    "#![allow(dead_code)]",
    "#![allow(clippy::too_many_lines)]",
    "#![allow(clippy::match_same_arms)]",
    "",
    "use macroquad::math::Rect;",
    "",
    "/// Fixed cell height shared by every glyph.",
    f"pub const CELL_H: f32 = {CELL_H}.0;",
    "",
    "/// Horizontal advance in pixels for `c` (space and unknown glyphs included).",
    "#[must_use]",
    "pub fn advance(c: char) -> i32 {",
    "    match c {",
]
for ch in CHARS:
    lines.append(f"        {esc(ch)} => {glyphs[ch][1]},")
lines.append("        _ => 0,")
lines.append("    }")
lines.append("}")
lines.append("")
lines.append("/// Source rect of `c` in the font atlas, or `None` if it draws nothing.")
lines.append("#[must_use]")
lines.append("pub fn glyph(c: char) -> Option<Rect> {")
lines.append("    let r = match c {")
for ch in CHARS:
    if ch in placements:
        x, y, w, h = placements[ch]
        lines.append(f"        {esc(ch)} => Rect {{ x: {x}.0, y: {y}.0, w: {w}.0, h: {h}.0 }},")
lines.append("        _ => return None,")
lines.append("    };")
lines.append("    Some(r)")
lines.append("}")
lines.append("")
open(os.path.join(SRC, "font.rs"), "w", newline="\n", encoding="utf-8").write("\n".join(lines))
print("src/font.rs", len(placements), "glyphs")

# Preview strip for visual check.
prev = Image.new("RGB", (300, 40), (200, 200, 200))
d = ImageDraw.Draw(prev)
comp = Image.alpha_composite(Image.new("RGBA", (ATLAS_W, atlas_h), (200, 200, 200, 255)),
                             Image.fromarray(atlas)).convert("RGB")
x = 2
for ch in "height WALK HEAVY 179 TROT":
    if ch == " ":
        x += 4
        continue
    px, py, w, h = placements[ch]
    prev.paste(comp.crop((px, py, px + w, py + h)), (x, 4))
    x += w + 1
prev.resize((300 * 3, 40 * 3), Image.NEAREST).save(
    r"C:\Users\MikaelBeyene\AppData\Local\Temp\claude\D--training-opensc\68a8ed9d-2ec2-4fb7-9ee2-ba32e48ffa1f\scratchpad\font_preview.png")
print("preview saved")
