// @generated by scripts/gen_atlas.py from reference/stuntcopter/png/sprites.json
// Do not edit by hand. Regenerate to change sprite rects.
//
// Each rect is a padded source rectangle within `atlas.png` (packed with a
// transparent gutter so nearest-neighbour sampling never bleeds neighbours).
//
// The full sprite set is generated up front; not every variant is drawn yet.
#![allow(dead_code)]
// Generated exhaustive match over every sprite; length is inherent.
#![allow(clippy::too_many_lines)]

use macroquad::math::Rect;

/// A sprite region within the packed atlas texture.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Sprite {
    /// `cloud_bottom`
    CloudBottom,
    /// `cloud_left`
    CloudLeft,
    /// `cloud_right`
    CloudRight,
    /// `copter_1`
    Copter1,
    /// `copter_2`
    Copter2,
    /// `copter_3`
    Copter3,
    /// `cross`
    Cross,
    /// `driver`
    Driver,
    /// `flip_01`
    Flip01,
    /// `flip_02`
    Flip02,
    /// `flip_03`
    Flip03,
    /// `flip_04`
    Flip04,
    /// `flip_05`
    Flip05,
    /// `flip_06`
    Flip06,
    /// `flip_07`
    Flip07,
    /// `flip_08`
    Flip08,
    /// `flip_09`
    Flip09,
    /// `flip_10`
    Flip10,
    /// `flip_11`
    Flip11,
    /// `flip_12`
    Flip12,
    /// `flip_13`
    Flip13,
    /// `flip_14`
    Flip14,
    /// `horse_dead`
    HorseDead,
    /// `man_drop1`
    ManDrop1,
    /// `man_drop2`
    ManDrop2,
    /// `man_drop3`
    ManDrop3,
    /// `man_drop4`
    ManDrop4,
    /// `man_drop5`
    ManDrop5,
    /// `man_hang`
    ManHang,
    /// `man_in_wagon`
    ManInWagon,
    /// `man_splat1`
    ManSplat1,
    /// `man_splat2`
    ManSplat2,
    /// `man_splat3`
    ManSplat3,
    /// `man_splat4`
    ManSplat4,
    /// `man_splat5`
    ManSplat5,
    /// `man_splat6`
    ManSplat6,
    /// `man_thumbdown`
    ManThumbdown,
    /// `man_thumbup`
    ManThumbup,
    /// `num_0`
    Num0,
    /// `num_1`
    Num1,
    /// `num_2`
    Num2,
    /// `num_3`
    Num3,
    /// `num_4`
    Num4,
    /// `num_5`
    Num5,
    /// `num_6`
    Num6,
    /// `num_7`
    Num7,
    /// `num_8`
    Num8,
    /// `num_9`
    Num9,
    /// `scorebox`
    Scorebox,
    /// `wagon_1`
    Wagon1,
    /// `wagon_2`
    Wagon2,
    /// `wagon_3`
    Wagon3,
}

impl Sprite {
    /// Source rectangle of this sprite within the atlas texture, in pixels.
    #[must_use]
    #[rustfmt::skip]
    pub const fn rect(self) -> Rect {
        match self {
            Self::CloudBottom => Rect { x: 231.0, y: 2.0, w: 210.0, h: 52.0 },
            Self::CloudLeft => Rect { x: 85.0, y: 2.0, w: 144.0, h: 72.0 },
            Self::CloudRight => Rect { x: 392.0, y: 85.0, w: 106.0, h: 48.0 },
            Self::Copter1 => Rect { x: 2.0, y: 179.0, w: 74.0, h: 26.0 },
            Self::Copter2 => Rect { x: 78.0, y: 179.0, w: 74.0, h: 26.0 },
            Self::Copter3 => Rect { x: 154.0, y: 179.0, w: 74.0, h: 26.0 },
            Self::Cross => Rect { x: 2.0, y: 2.0, w: 81.0, h: 81.0 },
            Self::Driver => Rect { x: 230.0, y: 179.0, w: 40.0, h: 22.0 },
            Self::Flip01 => Rect { x: 2.0, y: 136.0, w: 32.0, h: 41.0 },
            Self::Flip02 => Rect { x: 36.0, y: 136.0, w: 32.0, h: 41.0 },
            Self::Flip03 => Rect { x: 70.0, y: 136.0, w: 32.0, h: 41.0 },
            Self::Flip04 => Rect { x: 104.0, y: 136.0, w: 32.0, h: 41.0 },
            Self::Flip05 => Rect { x: 138.0, y: 136.0, w: 32.0, h: 41.0 },
            Self::Flip06 => Rect { x: 172.0, y: 136.0, w: 32.0, h: 41.0 },
            Self::Flip07 => Rect { x: 206.0, y: 136.0, w: 32.0, h: 41.0 },
            Self::Flip08 => Rect { x: 240.0, y: 136.0, w: 32.0, h: 41.0 },
            Self::Flip09 => Rect { x: 274.0, y: 136.0, w: 32.0, h: 41.0 },
            Self::Flip10 => Rect { x: 308.0, y: 136.0, w: 32.0, h: 41.0 },
            Self::Flip11 => Rect { x: 342.0, y: 136.0, w: 32.0, h: 41.0 },
            Self::Flip12 => Rect { x: 376.0, y: 136.0, w: 32.0, h: 41.0 },
            Self::Flip13 => Rect { x: 410.0, y: 136.0, w: 32.0, h: 41.0 },
            Self::Flip14 => Rect { x: 444.0, y: 136.0, w: 32.0, h: 41.0 },
            Self::HorseDead => Rect { x: 272.0, y: 179.0, w: 29.0, h: 22.0 },
            Self::ManDrop1 => Rect { x: 77.0, y: 207.0, w: 14.0, h: 16.0 },
            Self::ManDrop2 => Rect { x: 93.0, y: 207.0, w: 14.0, h: 16.0 },
            Self::ManDrop3 => Rect { x: 109.0, y: 207.0, w: 14.0, h: 16.0 },
            Self::ManDrop4 => Rect { x: 125.0, y: 207.0, w: 14.0, h: 16.0 },
            Self::ManDrop5 => Rect { x: 141.0, y: 207.0, w: 14.0, h: 16.0 },
            Self::ManHang => Rect { x: 157.0, y: 207.0, w: 14.0, h: 16.0 },
            Self::ManInWagon => Rect { x: 25.0, y: 231.0, w: 28.0, h: 10.0 },
            Self::ManSplat1 => Rect { x: 173.0, y: 207.0, w: 14.0, h: 16.0 },
            Self::ManSplat2 => Rect { x: 189.0, y: 207.0, w: 14.0, h: 16.0 },
            Self::ManSplat3 => Rect { x: 205.0, y: 207.0, w: 14.0, h: 16.0 },
            Self::ManSplat4 => Rect { x: 221.0, y: 207.0, w: 14.0, h: 16.0 },
            Self::ManSplat5 => Rect { x: 237.0, y: 207.0, w: 14.0, h: 16.0 },
            Self::ManSplat6 => Rect { x: 253.0, y: 207.0, w: 14.0, h: 16.0 },
            Self::ManThumbdown => Rect { x: 269.0, y: 207.0, w: 14.0, h: 16.0 },
            Self::ManThumbup => Rect { x: 285.0, y: 207.0, w: 14.0, h: 16.0 },
            Self::Num0 => Rect { x: 301.0, y: 207.0, w: 21.0, h: 15.0 },
            Self::Num1 => Rect { x: 324.0, y: 207.0, w: 21.0, h: 15.0 },
            Self::Num2 => Rect { x: 347.0, y: 207.0, w: 21.0, h: 15.0 },
            Self::Num3 => Rect { x: 370.0, y: 207.0, w: 21.0, h: 15.0 },
            Self::Num4 => Rect { x: 393.0, y: 207.0, w: 21.0, h: 15.0 },
            Self::Num5 => Rect { x: 416.0, y: 207.0, w: 21.0, h: 15.0 },
            Self::Num6 => Rect { x: 439.0, y: 207.0, w: 21.0, h: 15.0 },
            Self::Num7 => Rect { x: 462.0, y: 207.0, w: 21.0, h: 15.0 },
            Self::Num8 => Rect { x: 485.0, y: 207.0, w: 21.0, h: 15.0 },
            Self::Num9 => Rect { x: 2.0, y: 231.0, w: 21.0, h: 15.0 },
            Self::Scorebox => Rect { x: 2.0, y: 85.0, w: 388.0, h: 49.0 },
            Self::Wagon1 => Rect { x: 303.0, y: 179.0, w: 73.0, h: 22.0 },
            Self::Wagon2 => Rect { x: 378.0, y: 179.0, w: 73.0, h: 22.0 },
            Self::Wagon3 => Rect { x: 2.0, y: 207.0, w: 73.0, h: 22.0 },
        }
    }
}
