// @generated by scripts/gen_atlas.py from the original PICT resources.
// Do not edit by hand. Regenerate to change sprite rects.
//
// Each rect is a padded source rectangle within `atlas.png`.
#![allow(dead_code)]
#![allow(clippy::too_many_lines)]

use macroquad::math::Rect;

/// A sprite region within the packed atlas texture.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Sprite {
    /// `cloud_bottom`
    CloudBottom,
    /// `cloud_left`
    CloudLeft,
    /// `cloud_right`
    CloudRight,
    /// `copter_1`
    Copter1,
    /// `copter_2`
    Copter2,
    /// `copter_3`
    Copter3,
    /// `cross`
    Cross,
    /// `driver`
    Driver,
    /// `flip_01`
    Flip01,
    /// `flip_02`
    Flip02,
    /// `flip_03`
    Flip03,
    /// `flip_04`
    Flip04,
    /// `flip_05`
    Flip05,
    /// `flip_06`
    Flip06,
    /// `flip_07`
    Flip07,
    /// `flip_08`
    Flip08,
    /// `flip_09`
    Flip09,
    /// `flip_10`
    Flip10,
    /// `flip_11`
    Flip11,
    /// `flip_12`
    Flip12,
    /// `flip_13`
    Flip13,
    /// `flip_14`
    Flip14,
    /// `horse_dead`
    HorseDead,
    /// `man_drop1`
    ManDrop1,
    /// `man_drop2`
    ManDrop2,
    /// `man_drop3`
    ManDrop3,
    /// `man_drop4`
    ManDrop4,
    /// `man_drop5`
    ManDrop5,
    /// `man_hang`
    ManHang,
    /// `man_in_wagon`
    ManInWagon,
    /// `man_splat1`
    ManSplat1,
    /// `man_splat2`
    ManSplat2,
    /// `man_splat3`
    ManSplat3,
    /// `man_splat4`
    ManSplat4,
    /// `man_splat5`
    ManSplat5,
    /// `man_splat6`
    ManSplat6,
    /// `man_thumbdown`
    ManThumbdown,
    /// `man_thumbup`
    ManThumbup,
    /// `num_0`
    Num0,
    /// `num_1`
    Num1,
    /// `num_2`
    Num2,
    /// `num_3`
    Num3,
    /// `num_4`
    Num4,
    /// `num_5`
    Num5,
    /// `num_6`
    Num6,
    /// `num_7`
    Num7,
    /// `num_8`
    Num8,
    /// `num_9`
    Num9,
    /// `scorebox`
    Scorebox,
    /// `wagon_1`
    Wagon1,
    /// `wagon_2`
    Wagon2,
    /// `wagon_3`
    Wagon3,
}

impl Sprite {
    /// Source rectangle of this sprite within the atlas texture, in pixels.
    #[must_use]
    #[rustfmt::skip]
    pub const fn rect(self) -> Rect {
        match self {
            Self::CloudBottom => Rect { x: 2.0, y: 138.0, w: 210.0, h: 45.0 },
            Self::CloudLeft => Rect { x: 85.0, y: 2.0, w: 140.0, h: 73.0 },
            Self::CloudRight => Rect { x: 214.0, y: 138.0, w: 119.0, h: 44.0 },
            Self::Copter1 => Rect { x: 308.0, y: 185.0, w: 74.0, h: 26.0 },
            Self::Copter2 => Rect { x: 384.0, y: 185.0, w: 74.0, h: 26.0 },
            Self::Copter3 => Rect { x: 2.0, y: 228.0, w: 74.0, h: 26.0 },
            Self::Cross => Rect { x: 2.0, y: 2.0, w: 81.0, h: 81.0 },
            Self::Driver => Rect { x: 78.0, y: 228.0, w: 39.0, h: 22.0 },
            Self::Flip01 => Rect { x: 335.0, y: 138.0, w: 32.0, h: 41.0 },
            Self::Flip02 => Rect { x: 369.0, y: 138.0, w: 32.0, h: 41.0 },
            Self::Flip03 => Rect { x: 403.0, y: 138.0, w: 32.0, h: 41.0 },
            Self::Flip04 => Rect { x: 437.0, y: 138.0, w: 32.0, h: 41.0 },
            Self::Flip05 => Rect { x: 471.0, y: 138.0, w: 32.0, h: 41.0 },
            Self::Flip06 => Rect { x: 2.0, y: 185.0, w: 32.0, h: 41.0 },
            Self::Flip07 => Rect { x: 36.0, y: 185.0, w: 32.0, h: 41.0 },
            Self::Flip08 => Rect { x: 70.0, y: 185.0, w: 32.0, h: 41.0 },
            Self::Flip09 => Rect { x: 104.0, y: 185.0, w: 32.0, h: 41.0 },
            Self::Flip10 => Rect { x: 138.0, y: 185.0, w: 32.0, h: 41.0 },
            Self::Flip11 => Rect { x: 172.0, y: 185.0, w: 32.0, h: 41.0 },
            Self::Flip12 => Rect { x: 206.0, y: 185.0, w: 32.0, h: 41.0 },
            Self::Flip13 => Rect { x: 240.0, y: 185.0, w: 32.0, h: 41.0 },
            Self::Flip14 => Rect { x: 274.0, y: 185.0, w: 32.0, h: 41.0 },
            Self::HorseDead => Rect { x: 119.0, y: 228.0, w: 29.0, h: 22.0 },
            Self::ManDrop1 => Rect { x: 375.0, y: 228.0, w: 14.0, h: 16.0 },
            Self::ManDrop2 => Rect { x: 391.0, y: 228.0, w: 14.0, h: 16.0 },
            Self::ManDrop3 => Rect { x: 407.0, y: 228.0, w: 14.0, h: 16.0 },
            Self::ManDrop4 => Rect { x: 423.0, y: 228.0, w: 14.0, h: 16.0 },
            Self::ManDrop5 => Rect { x: 439.0, y: 228.0, w: 14.0, h: 16.0 },
            Self::ManHang => Rect { x: 455.0, y: 228.0, w: 14.0, h: 16.0 },
            Self::ManInWagon => Rect { x: 318.0, y: 256.0, w: 28.0, h: 10.0 },
            Self::ManSplat1 => Rect { x: 471.0, y: 228.0, w: 14.0, h: 16.0 },
            Self::ManSplat2 => Rect { x: 487.0, y: 228.0, w: 14.0, h: 16.0 },
            Self::ManSplat3 => Rect { x: 2.0, y: 256.0, w: 14.0, h: 16.0 },
            Self::ManSplat4 => Rect { x: 18.0, y: 256.0, w: 14.0, h: 16.0 },
            Self::ManSplat5 => Rect { x: 34.0, y: 256.0, w: 14.0, h: 16.0 },
            Self::ManSplat6 => Rect { x: 50.0, y: 256.0, w: 14.0, h: 16.0 },
            Self::ManThumbdown => Rect { x: 66.0, y: 256.0, w: 14.0, h: 16.0 },
            Self::ManThumbup => Rect { x: 82.0, y: 256.0, w: 14.0, h: 16.0 },
            Self::Num0 => Rect { x: 98.0, y: 256.0, w: 20.0, h: 15.0 },
            Self::Num1 => Rect { x: 120.0, y: 256.0, w: 20.0, h: 15.0 },
            Self::Num2 => Rect { x: 142.0, y: 256.0, w: 20.0, h: 15.0 },
            Self::Num3 => Rect { x: 164.0, y: 256.0, w: 20.0, h: 15.0 },
            Self::Num4 => Rect { x: 186.0, y: 256.0, w: 20.0, h: 15.0 },
            Self::Num5 => Rect { x: 208.0, y: 256.0, w: 20.0, h: 15.0 },
            Self::Num6 => Rect { x: 230.0, y: 256.0, w: 20.0, h: 15.0 },
            Self::Num7 => Rect { x: 252.0, y: 256.0, w: 20.0, h: 15.0 },
            Self::Num8 => Rect { x: 274.0, y: 256.0, w: 20.0, h: 15.0 },
            Self::Num9 => Rect { x: 296.0, y: 256.0, w: 20.0, h: 15.0 },
            Self::Scorebox => Rect { x: 2.0, y: 85.0, w: 387.0, h: 51.0 },
            Self::Wagon1 => Rect { x: 150.0, y: 228.0, w: 73.0, h: 22.0 },
            Self::Wagon2 => Rect { x: 225.0, y: 228.0, w: 73.0, h: 22.0 },
            Self::Wagon3 => Rect { x: 300.0, y: 228.0, w: 73.0, h: 22.0 },
        }
    }
}
